# Generated by Django 6.0.6 on 2026-06-09 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('etapa', 'Etapa de Projeto'), ('pagamento', 'Pagamento'), ('marco', 'Marco do Projeto')], default='etapa', max_length=10, verbose_name='Tipo')),
                ('data', models.DateField(verbose_name='Data')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data Fim')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='Link')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'verbose_name': 'Evento de Agenda',
                'verbose_name_plural': 'Eventos de Agenda',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('info', 'Informativo'), ('warning', 'Aviso'), ('danger', 'Urgente'), ('success', 'Sucesso')], default='info', max_length=10, verbose_name='Tipo')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='Link')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-criado_em'],
            },
        ),
    ]
