# Generated by Django 6.0.6 on 2026-06-08 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assinatura', models.ImageField(blank=True, null=True, upload_to='config/', verbose_name='Assinatura')),
                ('nome_administrador', models.CharField(default='Cleiton Simião Ndona', max_length=200, verbose_name='Nome do Administrador')),
                ('cargo', models.CharField(default='Administrador', max_length=200, verbose_name='Cargo')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração da Empresa',
                'verbose_name_plural': 'Configurações da Empresa',
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10, verbose_name='Tipo')),
                ('categoria', models.CharField(choices=[('honorarios', 'Honorários'), ('adiantamento', 'Adiantamento'), ('pagamento_projecto', 'Pagamento de Projecto'), ('outra_entrada', 'Outra Entrada'), ('material', 'Material'), ('servicos', 'Serviços'), ('salarios', 'Salários'), ('impostos', 'Impostos'), ('transporte', 'Transporte'), ('equipamento', 'Equipamento'), ('outra_saida', 'Outra Saída')], max_length=30, verbose_name='Categoria')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (MZN)')),
                ('data', models.DateField(verbose_name='Data')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('transferencia', 'Transferência Bancária'), ('deposito', 'Depósito'), ('dinheiro', 'Dinheiro'), ('mpesa', 'M-Pesa'), ('emola', 'E-Mola')], max_length=20, verbose_name='Forma de Pagamento')),
                ('documento', models.CharField(blank=True, help_text='Nº de recibo, transferência, etc.', max_length=50, verbose_name='Nº Documento')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.client', verbose_name='Cliente')),
                ('cotacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.quote', verbose_name='Cotação')),
            ],
            options={
                'verbose_name': 'Movimento de Caixa',
                'verbose_name_plural': 'Movimentos de Caixa',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
