# Generated by Django 6.0.6 on 2026-08-08 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_companysettings_cashflow'),
        ('projects', '0002_templateetapa_projectstage_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos', to='projects.project', verbose_name='Projeto'),
        ),
        migrations.AddField(
            model_name='quote',
            name='data_validade',
            field=models.DateField(blank=True, help_text='Data limite para o cliente decidir. Usada para calcular "Faltam X dias".', null=True, verbose_name='Validade'),
        ),
    ]
