# Generated by Django 6.0.6 on 2026-06-08 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Projeto')),
                ('tipo', models.CharField(choices=[('moradia', 'Moradia'), ('ampliacao', 'Ampliação'), ('renovacao', 'Renovação'), ('reforma', 'Reforma'), ('salao', 'Salão de Eventos'), ('pool', 'Pool Familiar'), ('comercial', 'Comercial'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('proposta', 'Proposta'), ('aprovado', 'Aprovado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='proposta', max_length=20, verbose_name='Status')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Total (MZN)')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_entrega', models.DateField(blank=True, null=True, verbose_name='Data de Entrega')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='crm.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(verbose_name='Ordem')),
                ('nome', models.CharField(max_length=200, verbose_name='Etapa')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_prevista', models.DateField(blank=True, null=True, verbose_name='Data Prevista')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('concluida', models.BooleanField(default=False, verbose_name='Concluída')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='projects.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'ordering': ['ordem'],
            },
        ),
    ]
