# Generated by Django 6.0.6 on 2026-07-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_projeto', models.CharField(choices=[('moradia', 'Moradia'), ('ampliacao', 'Ampliação'), ('renovacao', 'Renovação'), ('reforma', 'Reforma'), ('salao', 'Salão de Eventos'), ('pool', 'Pool Familiar'), ('comercial', 'Comercial'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo de Projeto')),
                ('ordem', models.PositiveIntegerField(verbose_name='Ordem')),
                ('nome', models.CharField(max_length=200, verbose_name='Etapa')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('dias_apos_inicio', models.PositiveIntegerField(default=0, help_text='Dias após a data de início para calcular data prevista', verbose_name='Dias após início')),
            ],
            options={
                'verbose_name': 'Etapa Padrão',
                'verbose_name_plural': 'Etapas Padrão',
                'ordering': ['tipo_projeto', 'ordem'],
            },
        ),
        migrations.AddField(
            model_name='projectstage',
            name='cor',
            field=models.CharField(default='secondary', help_text='Usado na barra de progresso', max_length=10, verbose_name='Cor'),
        ),
    ]
